### ISSUE TITLE
Great stuff in readme and repo start!

### ISSUE THREAD

**Issue by ddesmond** [dcourtois/clarisse_toolkit#1]
This readme should defo be in the clarisse manual online.
Could we maybe make a stripped down version with some sedmagic to remove / clean those terms we can ignore in the c manual?
so a python counterpart could be auto generated?

just throwing ideas
let me know what you think.

**Comment by dcourtois** [comment]
Hi, my opinion is: learning how to read it is very easy, and on the other hand creating some tools to automatically convert stuff to a more Python'esque syntax would be quite hard, would need to be maintained, etc.
So, not worth the effort. And it won't solve the problem that the errors often reported from Python contain C++ syntax, and those couldn't be translated (that would need to be changed from inside Clarisse, and it's not possible) So in any case it's better if people know how to convert between C++ syntax to Python.
Again, only my opinion. If someone makes a very good pull request to automatically generate good Python doc from the official ones, which works easily on the 3 platforms we support, I might accept it. I'm just not doing it myself, that's for sure :p
