### ISSUE TITLE
Bug: Not exiting properly 

### ISSUE THREAD

**Issue by ddesmond** [dcourtois/clarisse_toolkit#3]
After running latest QtHelper code, i find that the menus are not accesible anymore on hover, but you have to click, which seems like the app didint realy exit out cleanly. It happens will all our UIs running in Clarisse with the latest code.
Even the provided example in the code itself seems to not work.

An older version of QtHelper works fine, menus are accesible and seems that app exits cleanly.

Tried on Clarisse4 sp14 and sp17.

**Comment by dcourtois** [comment]
What do you mean exactly?
I've tried the `QtBasic.py` example with the latest version of the repo (I just changed the path in the `QtBasic.py` file to point to the repo) and it seemed to work as expected...

Can you be more precise in describing what happens exactly? If you attach some code, or an animated gif showing what goes wrong, that would help.

**Comment by ddesmond** [comment]
Closing cos of unlucky events with Clarisse.
Been a great ride!

Merry xmass @dcourtois
