### ISSUE TITLE
Bug: Not able to set style on app

### ISSUE THREAD

**Issue by ddesmond** [dcourtois/clarisse_toolkit#4]
Since there is no QAplication when starting with QtHelper.App, its imposible to set a style on the app itself.

**Comment by dcourtois** [comment]
? Did you try something like:

```
QtHelper.app().setStyleSheet(...)
```

**Comment by ddesmond** [comment]
im not sure how QtHelper.App() ended up in my code, that was the issue actualy.
style now works correctly.
closing this one.
